version: '3.7'

networks:
  inception_net:
    name: inception_net
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/schaya-ad/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/schaya-ad/data/mysql

services:
  nginx:
    container_name: nginx
    env_file: .env
    build: requirements/nginx/
    networks:
      - inception_net
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
  wordpress:
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    build: requirements/wordpress/
    networks:
      - inception_net
    container_name: wordpress
  mariadb:
    volumes:
      - db:/var/lib/mysql
    env_file: .env
    build: requirements/mariadb/
    networks:
      - inception_net
    container_name: mariadb
